spring:
  application:
    name: banking-api

  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: banking_user
    password: banking_pass

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
